"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { docsSearchIndex } from "@/content/docs-nav";

type Result = { url: string; title: string; excerpt?: string };

let pagefindPromise: Promise<any | null> | null = null;
function loadPagefind(): Promise<any | null> {
  if (!pagefindPromise) {
    // Generated by the `pagefind` postbuild step into /pagefind; absent in dev.
    pagefindPromise =
      // @ts-expect-error - generated at build time, no module on disk to resolve
      import(/* webpackIgnore: true */ /* turbopackIgnore: true */ "/pagefind/pagefind.js")
        .then(async (pf: any) => {
          await pf.init();
          return pf;
        })
        .catch(() => null);
  }
  return pagefindPromise;
}

function cleanUrl(url: string): string {
  return url.replace(/\.html$/, "").replace(/\/index$/, "") || "/";
}

function staticResults(q: string): Result[] {
  const query = q.toLowerCase();
  const list = query
    ? docsSearchIndex.filter((d) => `${d.title} ${d.keywords ?? ""}`.toLowerCase().includes(query))
    : docsSearchIndex;
  return list.map((d) => ({ url: d.href, title: d.title }));
}

/** The button that opens search. */
export function SearchTrigger({ onClick }: { onClick: () => void }) {
  return (
    <button type="button" onClick={onClick} className="search-btn">
      <svg width="14" height="14" viewBox="0 0 16 16" fill="none" aria-hidden="true">
        <circle cx="7" cy="7" r="4.5" stroke="currentColor" strokeWidth="1.5" />
        <path d="m11 11 3 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      </svg>
      <span>Search docs</span>
      <kbd>⌘K</kbd>
    </button>
  );
}

/** The single search modal. Full-text via Pagefind, with a static fallback. */
export function SearchModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const router = useRouter();
  const [query, setQuery] = useState("");
  const [sel, setSel] = useState(0);
  const [results, setResults] = useState<Result[]>(staticResults(""));
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (open) {
      setQuery("");
      setSel(0);
      setResults(staticResults(""));
      inputRef.current?.focus();
      loadPagefind();
    }
  }, [open]);

  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    (async () => {
      const q = query.trim();
      if (!q) {
        if (!cancelled) setResults(staticResults(""));
        return;
      }
      const pf = await loadPagefind();
      if (pf) {
        try {
          const search = await pf.search(q);
          const data = await Promise.all(search.results.slice(0, 8).map((r: any) => r.data()));
          if (!cancelled) {
            setResults(
              data.map((d: any) => ({
                url: cleanUrl(d.url),
                title: d.meta?.title || cleanUrl(d.url),
                excerpt: d.excerpt,
              })),
            );
            setSel(0);
            return;
          }
        } catch {
          /* fall through to static */
        }
      }
      if (!cancelled) {
        setResults(staticResults(q));
        setSel(0);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [query, open]);

  if (!open) return null;

  function go(url: string) {
    router.push(url);
    onClose();
  }

  function onInputKey(e: React.KeyboardEvent) {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      setSel((s) => Math.min(s + 1, results.length - 1));
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setSel((s) => Math.max(s - 1, 0));
    } else if (e.key === "Enter" && results[sel]) {
      go(results[sel].url);
    }
  }

  return (
    <div className="search-overlay" role="dialog" aria-modal="true" aria-label="Search documentation" onClick={onClose}>
      <div className="search" onClick={(e) => e.stopPropagation()}>
        <input
          ref={inputRef}
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={onInputKey}
          placeholder="Search documentation"
          aria-label="Search documentation"
        />
        <ul>
          {results.length === 0 ? (
            <li className="empty">No pages match. Try a command name or a config key.</li>
          ) : (
            results.map((r, i) => (
              <li key={r.url + i}>
                <button
                  type="button"
                  onMouseEnter={() => setSel(i)}
                  onClick={() => go(r.url)}
                  className={i === sel ? "on" : undefined}
                >
                  <span className="t">{r.title}</span>
                  {/* Pagefind excerpts are its own escaped HTML with <mark> highlights. */}
                  {r.excerpt ? (
                    <span className="x" dangerouslySetInnerHTML={{ __html: r.excerpt }} />
                  ) : (
                    <span className="x">{r.url}</span>
                  )}
                </button>
              </li>
            ))
          )}
        </ul>
      </div>
    </div>
  );
}
