"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { docsSearchIndex } from "@/content/docs-nav";
import { cn } from "@/lib/cn";

type Result = { url: string; title: string; excerpt?: string };

let pagefindPromise: Promise<any | null> | null = null;
function loadPagefind(): Promise<any | null> {
  if (!pagefindPromise) {
    // Generated by the `pagefind` postbuild step into /pagefind; absent in dev.
    pagefindPromise =
      // @ts-expect-error - generated at build time, no module on disk to resolve
      import(/* webpackIgnore: true */ "/pagefind/pagefind.js")
        .then(async (pf: any) => {
          await pf.init();
          return pf;
        })
        .catch(() => null);
  }
  return pagefindPromise;
}

function cleanUrl(url: string): string {
  return url.replace(/\.html$/, "").replace(/\/index$/, "") || "/";
}

function staticResults(q: string): Result[] {
  const query = q.toLowerCase();
  const list = query
    ? docsSearchIndex.filter((d) => `${d.title} ${d.keywords ?? ""}`.toLowerCase().includes(query))
    : docsSearchIndex;
  return list.map((d) => ({ url: d.href, title: d.title }));
}

/** The button that opens search. */
export function SearchTrigger({ onClick }: { onClick: () => void }) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="flex w-full items-center gap-2 rounded-md border border-hairline bg-surface-1 px-3 py-2 text-body-sm text-ink-tertiary transition-colors hover:border-hairline-strong"
    >
      <svg width="14" height="14" viewBox="0 0 16 16" fill="none" aria-hidden="true">
        <circle cx="7" cy="7" r="4.5" stroke="currentColor" strokeWidth="1.5" />
        <path d="m11 11 3 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      </svg>
      <span className="flex-1 text-left">Search docs</span>
      <kbd className="rounded border border-hairline bg-surface-2 px-1.5 text-caption text-ink-tertiary">⌘K</kbd>
    </button>
  );
}

/** The single search modal. Full-text via Pagefind, with a static fallback. */
export function SearchModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const router = useRouter();
  const [query, setQuery] = useState("");
  const [sel, setSel] = useState(0);
  const [results, setResults] = useState<Result[]>(staticResults(""));
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (open) {
      setQuery("");
      setSel(0);
      setResults(staticResults(""));
      inputRef.current?.focus();
      loadPagefind();
    }
  }, [open]);

  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    (async () => {
      const q = query.trim();
      if (!q) {
        if (!cancelled) setResults(staticResults(""));
        return;
      }
      const pf = await loadPagefind();
      if (pf) {
        try {
          const search = await pf.search(q);
          const data = await Promise.all(search.results.slice(0, 8).map((r: any) => r.data()));
          if (!cancelled) {
            setResults(
              data.map((d: any) => ({
                url: cleanUrl(d.url),
                title: d.meta?.title || cleanUrl(d.url),
                excerpt: d.excerpt,
              })),
            );
            setSel(0);
            return;
          }
        } catch {
          /* fall through to static */
        }
      }
      if (!cancelled) {
        setResults(staticResults(q));
        setSel(0);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [query, open]);

  if (!open) return null;

  function go(url: string) {
    router.push(url);
    onClose();
  }

  function onInputKey(e: React.KeyboardEvent) {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      setSel((s) => Math.min(s + 1, results.length - 1));
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setSel((s) => Math.max(s - 1, 0));
    } else if (e.key === "Enter" && results[sel]) {
      go(results[sel].url);
    }
  }

  return (
    <div
      className="fixed inset-0 z-[80] flex items-start justify-center bg-black/60 p-4 pt-[12vh]"
      role="dialog"
      aria-modal="true"
      aria-label="Search documentation"
      onClick={onClose}
    >
      <div
        className="w-full max-w-lg overflow-hidden rounded-xl border border-hairline-strong bg-surface-2 shadow-lift"
        onClick={(e) => e.stopPropagation()}
      >
        <input
          ref={inputRef}
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={onInputKey}
          placeholder="Search documentation…"
          className="w-full border-b border-hairline bg-transparent px-4 py-3.5 text-body text-ink placeholder:text-ink-tertiary focus:outline-none"
        />
        <ul className="max-h-[52vh] overflow-auto p-2">
          {results.length === 0 ? (
            <li className="px-3 py-6 text-center text-body-sm text-ink-tertiary">No results.</li>
          ) : (
            results.map((r, i) => (
              <li key={r.url + i}>
                <button
                  type="button"
                  onMouseEnter={() => setSel(i)}
                  onClick={() => go(r.url)}
                  className={cn(
                    "flex w-full flex-col items-start gap-1 rounded-md px-3 py-2 text-left",
                    i === sel ? "bg-surface-3" : "hover:bg-surface-3/60",
                  )}
                >
                  <span className="text-body-sm text-ink">{r.title}</span>
                  {r.excerpt ? (
                    <span
                      className="line-clamp-2 text-caption text-ink-subtle [&_mark]:rounded-sm [&_mark]:bg-primary/25 [&_mark]:text-ink"
                      dangerouslySetInnerHTML={{ __html: r.excerpt }}
                    />
                  ) : (
                    <span className="text-caption text-ink-tertiary">{r.url}</span>
                  )}
                </button>
              </li>
            ))
          )}
        </ul>
      </div>
    </div>
  );
}
